name: Publish npm package

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the package
        working-directory: volts-connector
        run: npm run build # Make sure your build script is defined in package.json

      - name: Publish to npm
        working-directory: volts-connector
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
